---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubenotify-service-account
  namespace: kubenotify
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubenotify-cluster-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", ...]
  verbs: ["get", "list", ...]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubenotify-role-binding
subjects:
- kind: ServiceAccount
  name: kubenotify-service-account
  namespace: kubenotify
roleRef:
  kind: ClusterRole
  name: kubenotify-cluster-role
  apiGroup: rbac.authorization.k8s.io